# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Startup',
            new_name='startups',
        ),
    ]
