# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-12 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=' ', max_length=30),
        ),
    ]
