# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-12 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
